apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: db
spec:
  replicas: 1
  template:
    metadata:
      name: mongo-pod
      labels:
        app: db
        tier: db
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
  selector:
    matchLabels:
      app: db
      tier: db

---

apiVersion: v1
kind: Service
metadata:
  name: dbsvc
  labels:
    name: db-service
    app: counter-app
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: db
    tier: db

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
  labels:
    app: webapp
spec:
  replicas: 1
  template:
    metadata:
      name: web-pod
      labels:
        app: webapp
        tier: frontend
    spec:
      containers:
        - name: webapp-container
          image: therealsharip/counter1
          ports:
            - containerPort: 3000
  selector:
    matchLabels:
      app: webapp
      tier: frontend

---

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: webapp
    tier: frontend